title: Esteban Guevara López
author:
  email: eguevaralopez@gmail.com
paypal: estebanguevaralopez
description: un blog no-lineal, de un mae no-lineal
url: "http://eguevaralopez.github.io"
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
minima:
  date_format: "%Y-%m-%d"
  skin: classic #classic dark solarized solarized-dark

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - running.md
# - acerca.md

footer_pages:
#  - pc.md
#  - cv.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

kramdown:
  math_engine: null
